# Generated by Django 5.1.12 on 2025-12-06 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True), ('is_default', True)), fields=('user',), name='unique_default_portfolio_per_user'),
        ),
    ]
