# Generated by Django 5.1.12 on 2025-09-19 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccounts',
            fields=[
                ('Username', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('HashedPassword', models.CharField(max_length=255)),
                ('Date_Created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavedRuns',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_Created', models.DateTimeField(auto_now_add=True)),
                ('SpotPrice', models.FloatField()),
                ('StrikePrice', models.FloatField()),
                ('TimeToExpiry', models.FloatField()),
                ('RiskFreeRate', models.FloatField()),
                ('DividendYield', models.FloatField()),
                ('Volatility', models.FloatField()),
                ('Price', models.FloatField()),
                ('Rho', models.FloatField()),
                ('Gamma', models.FloatField()),
                ('OptionType', models.CharField(choices=[('Call', 'Call'), ('Put', 'Put')], max_length=4)),
                ('ImpliedVolatility', models.FloatField()),
                ('Theta', models.FloatField()),
                ('Vega', models.FloatField()),
                ('Delta', models.FloatField()),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.useraccounts')),
            ],
        ),
        migrations.CreateModel(
            name='OPENAIAPIRESPONSE',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_Added', models.DateTimeField(auto_now_add=True)),
                ('UserQuestion', models.TextField()),
                ('APIResponse', models.TextField()),
                ('SavedRun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.savedruns')),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.useraccounts')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_Created', models.DateTimeField(auto_now_add=True)),
                ('Action', models.CharField(choices=[('Login', 'Login'), ('Logout', 'Logout')], max_length=10)),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.useraccounts')),
            ],
        ),
    ]
