# Generated by Django 5.1.12 on 2025-12-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedruns',
            name='OptionStyle',
            field=models.CharField(choices=[('EURO', 'European'), ('AMER', 'American')], default='EURO', max_length=8),
        ),
    ]
