# Generated by Django 5.1.12 on 2025-12-04 02:36

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('underlying_symbol', models.CharField(max_length=10)),
                ('option_side', models.CharField(choices=[('CALL', 'Call'), ('PUT', 'Put')], max_length=4)),
                ('option_style', models.CharField(choices=[('EUROPEAN', 'European'), ('AMERICAN', 'American')], max_length=10)),
                ('strike', models.DecimalField(decimal_places=4, max_digits=18)),
                ('expiry', models.DateField()),
                ('multiplier', models.IntegerField(default=100)),
                ('contract_symbol', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('underlying_symbol', 'option_side', 'option_style', 'strike', 'expiry', 'multiplier')},
            },
        ),
        migrations.CreateModel(
            name='OptionPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('avg_cost', models.DecimalField(decimal_places=4, max_digits=18)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='optnstrdr.optioncontract')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_positions', to='api.portfolio')),
            ],
            options={
                'unique_together': {('portfolio', 'contract')},
            },
        ),
        migrations.CreateModel(
            name='OptionTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('order_type', models.CharField(choices=[('MARKET', 'Market'), ('LIMIT', 'Limit')], default='MARKET', max_length=10)),
                ('status', models.CharField(choices=[('FILLED', 'Filled'), ('CANCELLED', 'Cancelled')], default='FILLED', max_length=10)),
                ('fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('underlying_price_at_execution', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('realized_pl', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='optnstrdr.optioncontract')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_trades', to='api.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='OptionValuationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('mark_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('underlying_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('unrealized_pl', models.DecimalField(decimal_places=4, max_digits=18)),
                ('delta', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('gamma', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('theta', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('vega', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('rho', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('source', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='optnstrdr.optioncontract')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_valuations', to='api.portfolio')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valuations', to='optnstrdr.optionposition')),
            ],
            options={
                'indexes': [models.Index(fields=['portfolio', 'snapshot_time'], name='optnstrdr_o_portfol_5fd041_idx'), models.Index(fields=['contract', 'snapshot_time'], name='optnstrdr_o_contrac_43a712_idx')],
            },
        ),
    ]
