# Generated by Django 5.1.12 on 2025-12-04 20:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('optnstrdr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('underlying_price_at_exercise', models.DecimalField(decimal_places=4, max_digits=18)),
                ('intrinsic_value_per_contract', models.DecimalField(decimal_places=4, max_digits=18)),
                ('intrinsic_value_total', models.DecimalField(decimal_places=4, max_digits=18)),
                ('option_realized_pl', models.DecimalField(decimal_places=4, max_digits=18)),
                ('cash_delta', models.DecimalField(decimal_places=4, max_digits=18)),
                ('exercised_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='optnstrdr.optioncontract')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_exercises', to='api.portfolio')),
            ],
            options={
                'indexes': [models.Index(fields=['portfolio', 'exercised_at'], name='optnstrdr_o_portfol_15d855_idx'), models.Index(fields=['contract', 'exercised_at'], name='optnstrdr_o_contrac_0cf861_idx')],
            },
        ),
    ]
